name: " Solicitud de configuraci贸n"
description: "Pide una configuraci贸n de ajuste para un veh铆culo que no est谩 en la lista"
title: "[Solicitud] Ajuste para: "
labels: ["Solicitud"]
assignees:
  - "EDDIT8"
body:
  - type: markdown
    attributes:
      value: "###  Informaci贸n del veh铆culo\nPor favor, llena los datos del coche para que podamos agregarlo."

  - type: input
    id: marca
    attributes:
      label: "Marca"
      description: "Ejemplo: Toyota"
      placeholder: "Ejemplo: Nissan"
    validations:
      required: true

  - type: input
    id: modelo
    attributes:
      label: "Modelo"
      description: "Ejemplo: Supra"
      placeholder: "Ejemplo: Skyline GT-R"
    validations:
      required: true

  - type: textarea
    id: detalles
    attributes:
      label: "Detalles adicionales"
      description: "Cualquier detalle adicional sobre la configuraci贸n del coche."
      placeholder: "Ejemplo: Este coche tiene tracci贸n AWD y 500HP."
    validations:
      required: false
